spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  data:
    mongodb:
      host: localhost
      port: 27017
      database: buyit

gemini:
  api:
    key: ${GEMINI_API_KEY:your-api-key-here}